name: ov_respy

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy
  - flake8
  - pyyaml
  - codecov
  - pip
  - pip:
      - pre-commit
      - respy
      - estimagic>=0.0.9
